version: "3.7"
services:
 api:
  build:
   context: .
   target: development
  volumes:
   - ./:/app
  depends_on:
      - db
  ports:
   - 4000:4000
  command: npm run dev
 db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
 adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080